In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import seaborn as sns
import os.path
import ast

In [12]:
matplotlib.rcParams['figure.figsize'] = (12, 10)

## Introduction

## Data Exploration

In [13]:
data_file = 'data.csv'

if not os.path.exists(data_file):
    print('Cannot find data')

In [14]:
df = pd.read_csv('data.csv', sep=',', header=0)

In [15]:
df.head()

,source_file,lineno,ast_depth,num_test_cover,num_executed,num_assert_tm,num_assert_tc,mutant_operator_type,function_max_depth,function_avg_depth,class_max_depth,lineno_loc,loc_list,mutation_number,status
0,src/calculator.py,3,3,2,4,3,20,AOD,10,8.5,10,5,"['8:14', '16:17']",1,killed
1,src/calculator.py,3,4,2,4,3,20,AOR,10,8.5,10,5,"['8:14', '16:17']",2,killed
2,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],3,killed
3,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],4,killed
4,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],5,survived

In [16]:
df

,source_file,lineno,ast_depth,num_test_cover,num_executed,num_assert_tm,num_assert_tc,mutant_operator_type,function_max_depth,function_avg_depth,class_max_depth,lineno_loc,loc_list,mutation_number,status
0,src/calculator.py,3,3,2,4,3,20,AOD,10,8.5,10,5,"['8:14', '16:17']",1,killed
1,src/calculator.py,3,4,2,4,3,20,AOR,10,8.5,10,5,"['8:14', '16:17']",2,killed
2,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],3,killed
3,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],4,killed
4,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0,['20:21'],5,survived
5,src/calculator.py,7,4,1,1,1,20,AOR,7,7.0,10,0,['20:21'],6,killed
6,src/calculator.py,7,4,1,1,1,20,AOR,7,7.0,10,0,['20:21'],7,killed
7,src/calculator.py,7,4,1,1,1,20,AOR,7,7.0,10,0,['20:21'],8,killed
8,src/calculator.py,11,3,1,1,1,20,ASR,7,7.0,10,0,['23:24'],9,killed
9,src/calculator.py,18,4,1,1,1,20,BCR,7,7.0,10,0,['26:27'],10,killed
10,src/calculator.py,23,3,1,1,1,20,COD,7,7.0,10,0,['29:30'],11,killed
11,src/calculator.py,17,3,1,4,1,20,COI,7,7.0,10,0,['26:27'],12,killed
12,src/calculator.py,23,2,1,1,1,20,COI,7,7.0,10,0,['29:30'],13,killed
13,src/calculator.py,29,2,1,1,1,20,COI,7,7.0,10,0,['32:33'],14,killed
14,src/calculator.py,90,2,1,1,1,20,COI,7,7.0,10,0,['60:61'],15,survived
15,src/calculator.py,92,2,0,0,0,0,COI,0,0.0,0,0,[],16,survived
16,src/calculator.py,106,2,1,1,1,20,COI,7,7.0,10,0,['69:70'],17,survived
17,src/calculator.py,7,4,1,1,1,20,CRP,7,7.0,10,0,['20:21'],18,killed
18,src/calculator.py,16,3,1,4,1,20,CRP,7,7.0,10,0,['26:27'],19,killed
19,src/calculator.py,16,3,1,4,1,20,CRP,7,7.0,10,0,['26:27'],20,killed
20,src/calculator.py,17,6,1,4,1,20,CRP,7,7.0,10,0,['26:27'],21,killed
21,src/calculator.py,17,6,1,4,1,20,CRP,7,7.0,10,0,['26:27'],22,killed
22,src/calculator.py,35,3,1,1,1,20,CRP,7,7.0,10,0,['35:36'],23,killed
23,src/calculator.py,36,3,1,1,1,20,CRP,7,7.0,10,0,['35:36'],24,killed
24,src/calculator.py,36,3,1,1,1,20,CRP,7,7.0,10,0,['35:36'],25,killed
25,src/calculator.py,57,6,0,0,0,0,CRP,0,0.0,0,0,[],26,survived
26,src/calculator.py,57,6,0,0,0,0,CRP,0,0.0,0,0,[],27,survived
27,src/calculator.py,61,3,0,1,0,0,CRP,0,0.0,0,0,[],28,survived
28,src/calculator.py,65,3,0,1,0,0,CRP,0,0.0,0,0,[],29,killed
29,src/calculator.py,86,4,1,1,1,20,CRP,6,6.0,10,1,['56:58'],30,survived
30,src/calculator.py,41,2,0,1,0,0,DDL,0,0.0,0,0,[],31,survived
31,src/calculator.py,49,3,0,0,0,0,EHD,0,0.0,0,0,[],32,survived
32,src/calculator.py,56,3,0,0,0,0,EXS,0,0.0,0,0,[],33,survived
33,src/calculator.py,84,2,0,1,0,0,IOP,0,0.0,0,0,[],34,killed
34,src/calculator.py,90,5,1,1,1,20,LCR,7,7.0,10,0,['60:61'],35,survived
35,src/calculator.py,92,5,0,0,0,0,LCR,0,0.0,0,0,[],36,survived
36,src/calculator.py,97,3,1,1,1,20,LOD,7,7.0,10,0,['63:64'],37,survived
37,src/calculator.py,101,4,1,1,1,20,LOR,7,7.0,10,0,['66:67'],38,survived
38,src/calculator.py,102,4,1,1,1,20,LOR,7,7.0,10,0,['66:67'],39,survived
39,src/calculator.py,17,6,1,4,1,20,ROR,7,7.0,10,0,['26:27'],40,survived
40,src/calculator.py,106,5,1,1,1,20,ROR,7,7.0,10,0,['69:70'],41,survived
41,src/calculator.py,106,5,1,1,1,20,ROR,7,7.0,10,0,['69:70'],42,killed
42,src/calculator.py,84,2,0,1,0,0,SCD,0,0.0,0,0,[],43,survived
43,src/calculator.py,116,2,0,1,0,0,SCD,0,0.0,0,0,[],44,survived

## Data Cleaning

In [17]:
df.isnull().values.any()

False

In [18]:
X = df.drop(labels=['status','mutation_number', 'loc_list'], axis=1)
y = df[['status']]
use_for_semantic_analysis = df[['loc_list']]

In [19]:
X[0:5]

,source_file,lineno,ast_depth,num_test_cover,num_executed,num_assert_tm,num_assert_tc,mutant_operator_type,function_max_depth,function_avg_depth,class_max_depth,lineno_loc
0,src/calculator.py,3,3,2,4,3,20,AOD,10,8.5,10,5
1,src/calculator.py,3,4,2,4,3,20,AOR,10,8.5,10,5
2,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0
3,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0
4,src/calculator.py,7,5,1,1,1,20,AOR,7,7.0,10,0

In [20]:
y[0:5]

     status
0    killed
1    killed
2    killed
3    killed
4  survived